# Generated by Django 4.2.13 on 2026-05-27 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('L', 'Litre'), ('kg', 'Kilogram'), ('kWh', 'Kilowatt-hour'), ('m3', 'Cubic metre'), ('km', 'Kilometre'), ('night', 'Hotel night')], max_length=10)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(max_length=200)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility (Electricity)'), ('travel', 'Corporate Travel')], help_text='Which of the three source types produced this record.', max_length=20)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 - Direct'), ('2', 'Scope 2 - Electricity'), ('3', 'Scope 3 - Indirect')], max_length=1)),
                ('category', models.CharField(choices=[('fuel_diesel', 'Fuel - Diesel'), ('fuel_petrol', 'Fuel - Petrol/Gasoline'), ('fuel_natural_gas', 'Fuel - Natural Gas'), ('fuel_lpg', 'Fuel - LPG'), ('electricity', 'Electricity'), ('travel_flight', 'Travel - Flight'), ('travel_hotel', 'Travel - Hotel'), ('travel_ground', 'Travel - Ground Transport'), ('procurement', 'Procurement')], max_length=50)),
                ('activity_description', models.TextField(help_text="Human-readable description: 'Diesel purchase, Plant DE-01, vendor 4000123'")),
                ('raw_value', models.DecimalField(decimal_places=4, help_text='Quantity as reported in the source file (before unit conversion)', max_digits=18)),
                ('raw_unit', models.CharField(help_text="Unit as reported in source (e.g. 'L', 'GAL', 'KWH', 'M3', 'KG')", max_length=20)),
                ('normalized_value', models.DecimalField(decimal_places=4, help_text='Value in the unit expected by the emission factor (after conversion)', max_digits=18)),
                ('normalized_unit', models.CharField(help_text="Standard unit used for emission factor lookup (e.g. 'L', 'kWh', 'km')", max_length=10)),
                ('unit_conversion_factor', models.DecimalField(decimal_places=6, default=1.0, help_text='Multiplier applied to raw_value to get normalized_value', max_digits=12)),
                ('emission_factor_value_used', models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of factor at time of calculation. Factor may change later.', max_digits=12, null=True)),
                ('normalized_value_kg_co2e', models.DecimalField(blank=True, decimal_places=4, help_text='Final emission value in kgCO2e. This is what goes to the report.', max_digits=18, null=True)),
                ('activity_date', models.DateField(help_text='Date of the activity (not the ingestion date)')),
                ('reporting_period_start', models.DateField(help_text='Start of the reporting period this record belongs to (usually Jan 1)')),
                ('reporting_period_end', models.DateField(help_text='End of the reporting period (usually Dec 31)')),
                ('location_code', models.CharField(blank=True, max_length=100)),
                ('location_name', models.CharField(blank=True, max_length=500)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=3)),
                ('source_metadata', models.JSONField(blank=True, default=dict, help_text='Source-specific fields (PO number, meter ID, flight route, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged - Needs Attention'), ('approved', 'Approved'), ('locked', 'Locked for Audit'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Set by the parser if the value looks anomalous (e.g. 10x the rolling avg)')),
                ('suspicion_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, help_text="The factor applied. Protected so we don't lose history.", null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor')),
                ('ingestion_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='ingest.ingestionrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source_row', models.OneToOneField(blank=True, help_text='The raw row this record was derived from. Null if manually entered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_record', to='ingest.rawrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecordEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='emissions_e_tenant__5a7e62_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='emissions_e_tenant__80b9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'activity_date'], name='emissions_e_tenant__a4863c_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'reporting_period_start', 'reporting_period_end'], name='emissions_e_tenant__068ff7_idx'),
        ),
    ]
